In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("ecommerce_orders.csv")

In [4]:
df.head(3)

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05

In [5]:
df.info()
df.dtypes
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    str
 2   Order_ID        103 non-null    str
 3   Order_Date      103 non-null    str
 4   Product         103 non-null    str
 5    Category       95 non-null     str
 6   Quantity        98 non-null     str
 7   Price           98 non-null     str
 8   Payment_Method  103 non-null    str
 9   Status          103 non-null    str
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), str(9)
memory usage: 9.0 KB

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          8
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [6]:
#Convert Quantity and Price to numbers
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

In [7]:
#Chcek duplicates
df.duplicated().sum()

np.int64(1)

In [8]:
df = df.drop_duplicates()

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
#Find missing values
df.isnull().sum()

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          8
Quantity           6
Price              9
Payment_Method     0
Status             0
Total             14
dtype: int64

In [12]:
# Check column names
print(df.columns)

Index(['ID', ' Customer_Name', 'Order_ID', 'Order_Date', 'Product',
       ' Category', 'Quantity', 'Price', 'Payment_Method', 'Status', 'Total'],
      dtype='str')

In [13]:
# Clean column names by stripping whitespace
df.columns = df.columns.str.strip()

In [14]:
print(df.columns)

Index(['ID', 'Customer_Name', 'Order_ID', 'Order_Date', 'Product', 'Category',
       'Quantity', 'Price', 'Payment_Method', 'Status', 'Total'],
      dtype='str')

In [15]:
#Fill missing category values with 'Unknown'
df["Category"] = df["Category"].fillna("Unknown")

In [16]:
#Fill missing quantity values with median
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

In [17]:
##Fill missing price values with median
df["Price"] = df["Price"].fillna(df["Price"].median())

In [18]:
df["Total"] = df["Quantity"] * df["Price"]

In [19]:
df.isnull().sum()

ID                0
Customer_Name     0
Order_ID          0
Order_Date        0
Product           0
Category          0
Quantity          0
Price             0
Payment_Method    0
Status            0
Total             0
dtype: int64

In [24]:
#Fix Date Format
df["Order Date1"] = pd.to_datetime(df["Order_Date"], errors="coerce")
df["Order Date1"].head()

0   2024-11-22
1   2025-07-05
2   2024-12-23
3   2025-03-19
4   2025-10-20
Name: Order Date1, dtype: datetime64[us]

In [27]:
#Create Revenue Column
df["Revenue"] = df["Quantity"] * df["Price"]

In [29]:
df.head()

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total,Revenue,Order Date1
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00,114.00,2024-11-22
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2.0,538.35,PayPal,Processing,1076.70,1076.70,2025-07-05
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05,389.05,2024-12-23
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5.0,233.92,PayPal,Processing,1169.60,1169.60,2025-03-19
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51,552.51,2025-10-20

In [30]:
df.to_csv("cleaned_orders.csv", index=False)